---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - harvesterhci.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.harvesterhci.io
  resources:
  - upgradeplans
  - versions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.harvesterhci.io
  resources:
  - upgradeplans/finalizers
  - versions/finalizers
  verbs:
  - update
- apiGroups:
  - management.harvesterhci.io
  resources:
  - upgradeplans/status
  - versions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - upgrade.cattle.io
  resources:
  - plans
  verbs:
  - create
  - get
  - list
  - update
  - watch
