# This rule is not used by the project upgrade-toolkit itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to management.harvesterhci.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: upgrade-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: upgradeplan-viewer-role
rules:
- apiGroups:
  - management.harvesterhci.io
  resources:
  - upgradeplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.harvesterhci.io
  resources:
  - upgradeplans/status
  verbs:
  - get
