# This rule is not used by the project upgrade-toolkit itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over management.harvesterhci.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: upgrade-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: version-admin-role
rules:
- apiGroups:
  - management.harvesterhci.io
  resources:
  - versions
  verbs:
  - '*'
- apiGroups:
  - management.harvesterhci.io
  resources:
  - versions/status
  verbs:
  - get
